PaginaWeb/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('PaginaWebApp.urls')),

    path('servicios/',include('servicios.urls')),

    path('blog/',include('blog.urls')),

    path('contacto/',include('contacto.urls')),

    path('tienda/',include('tienda.urls')),

    path('carro/',include('carro.urls')),

    path('process_payment/',include('process_payment.urls')),
] 

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('',views.blog, name="Blog"),
    path('categorias/<categoria_id>/',views.categoria, name="categoria"),
]

carro/urls.py
from django.urls import path

from . import views

app_name ="carro"

urlpatterns = [
   
path("agregar/<int:producto_id>/",views.agregar_producto, name="agregar"),
path("eliminar/<int:producto_id>/",views.eliminar_producto, name="eliminar"),
path("restar/<int:producto_id>/",views.restar_producto, name="restar"),
path("limpiar/",views.limpiar_carro, name="limpiar"),
path("comprar/",views.comprar, name="comprar"),

]

tienda/urls.py
from django.test import TestCase

from django.urls import path

from . import views


urlpatterns = [
   
 path('',views.tienda, name="Tienda"),
 path('comprar/',views.comprar, name="Comprar"),

]

tienda/models.py
from django.db import models

# Create your models here.


class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'CategoríaProducto'
        verbose_name_plural = 'CategoríaProductos'

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null=True, blank= True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True) 

    class Meta:
        verbose_name ="Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.nombre

carro/views.py
from django.shortcuts import render
from .carro import Carro

from tienda.models import Producto

from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Tienda")

def eliminar_producto(request, producto_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Tienda")

def restar_producto(request, producto_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Tienda")

def limpiar_carro(request):

    carro = Carro(request)

    carro.limpiar_carro()

    return redirect("Tienda")

def comprar(request):

    carro = Carro(request)

    carro.comprar(request)

    return redirect("Comprar")

tienda/views.py
from django.shortcuts import render
from tienda.models import CategoriaProd, Producto


# SDK de Mercado Pago
import mercadopago
# Agrega credenciales
sdk = mercadopago.SDK("TEST-1682191286570055-072420-081eaf21dbcddd9e349e4e05abdcad98-97637851")

# Create your views here.

def tienda(request):

    categoria = CategoriaProd.objects.all()
    productos = Producto.objects.all()

    return render(request,"tienda/tienda.html", {"categoria":categoria, "productos":productos} )

def comprar(request):

    categoria = CategoriaProd.objects.all()
    productos = Producto.objects.all()

    return render(request,"tienda/comprar.html", {"categoria":categoria, "productos":productos} )

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
  <thead>
    <tr>
      <th colspam="3" class="text-center">Carro de compras</th>
      <th>
        <a href="{% url 'carro:limpiar' %}" class="btn btn-sm btn-danger"
          >Vaciar carrito</a
        >
      </th>
    </tr>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Suma</th>
    </tr>
  </thead>

  <tbody>
    {% if request.session.carro.items %}
        {% for key, value in request.session.carro.items %}
    <tr class="text-center">
      <td>{{value.nombre}}</td>
      <td>{{value.cantidad}}</td>
      <td>
        <a
          href="{% url 'carro:agregar' value.producto_id %}"
          class="btn btn-sm btn-success"
          >+</a
        >
        <a
          href="{% url 'carro:restar' value.producto_id %}"
          class="btn btn-sm btn-danger"
          >-</a
        ><br />

        {{value.precio}}
      </td>
    </tr>
        {% endfor %}
    {% else %}
    <tr>
      <td colspam="3">
        <div class="alert alert-danger text-center">Sin productos.</div>
      </td>
    </tr>

    {% endif %}
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">Total: $ {{importe_total_carro}}</td>
    </tr>
    {% if request.user.is_authenticated == True %}
    <tr>
      <td>
        <a href="{% url 'carro:comprar' %}" class="btn btn-sm btn-success"
          >Comprar</a
        >
      </td>
    </tr>
    {% else %}
    <tr>
  <td>
    Debes iniciar sesión para comprar.
  </td>
  </tr>
    {% endif %}
  </tfoot>
</table>